FUN_STRINGS = (
    "Why did the cat wear a fancy dress? She was feline fabulous!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the coffee file a police report? It got mugged!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the banana go to the doctor? Because it wasn't peeling well!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the gardener plant a light bulb? He wanted to grow a power plant!",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one!",
    "Why did the farmer win an award? Because he was outstanding in his field!",
    "Why did the scientist install a knocker on his door? He wanted to win the No-bell prize!",
    "Why did the dog sit in the shade? Because he didn't want to be a hot dog!",
    "Why did the robber take a bath? He wanted to make a clean getaway!",
    "Why did the grape stop in the middle of the road? Because it ran out of juice!",
    "Why don't oysters give to charity? Because they're shellfish!",
    "Why don't seagulls fly by the bay? Because then they would be bagels!",
    "Why did the chicken join a band? Because it already had drumsticks!",
    "Why did the cookie go to the doctor? Because it was feeling crummy!",
    "Why did the astronaut break up with his girlfriend? Because he needed more space!",
    "Why did the fish blush? Because it saw the ocean's bottom!",
    "Why did the antelope go to the psychiatrist? Because he was having impalas!",
    "Why did the mushroom go to the party? Because he was a fungi!",
    "Why don't aliens eat clowns? Because they taste funny!",
    "Why don't ants get sick? Because they have tiny ant-bodies!",
    "Why did the banana go to the doctor? Because it had a-peel!",
    "Why don't sharks live in the jungle? Because they can't climb trees!",
    "Why don't fish play basketball? They're afraid of the net!",
    "Why did the dumb person go to the movies with a bucket? To get a "pop"corn!",
    "Why did the egg go to the seance? To talk to the omelette of the other side!",
    "Why did the robot go on a diet? To reduce his oil intake!",
    "Why did the bear dissolve in water? Because he was polar!",
    "Why did the fish blush? Because it saw the ocean's bottom!",
    "Why did the snail paint an "S" on his car? So people would say "Look at that S-car-go!"",
    "Why did the tree go to the dentist? To get a root canal!",
    "Why don't bees ever get married? Because they have too many honeys!",
    "Why did the man with a broken leg go to see a doctor? He needed a knee replacement!",
    "Why did the farmer plant corn in his garden? He wanted to make popcorn!",
    "Why did the banana go to the doctor? It wasn't peeling well!",
    "Why did the can crusher quit his job? Because it was soda pressing!",
    "Why did the jellybean go to school? To become a smartie!",
)
